/**
 * Identity resolution — deterministic candidate generation.
 *
 * The rule this file guards: candidates are generated by code you can read, the
 * model may only REORDER them, and NOTHING here writes a link. A candidate is a
 * question to ask a human ("are you the Ann Lee listed as Executive Officer of
 * Acme Robotics?"), never an answer.
 */
import { describe, it, expect } from "vitest";
import {
  normalizePersonName,
  normalizeCompanyName,
  companySlug,
  emailDomain,
  isFreeEmailDomain,
  domainFromUrl,
} from "../src/core/attribution/normalize";
import { generateCandidates, applyRanking, CANDIDATE_FLOOR, type UserRef } from "../src/core/attribution/identity";

const users: UserRef[] = [
  { id: "u-ann", handle: "annlee", displayName: "Ann Lee", email: "ann@acmerobotics.com" },
  { id: "u-ann2", handle: "aleeSF", displayName: "A. Lee", email: "a.lee@gmail.com" },
  { id: "u-bo", handle: "bo", displayName: "Bo Q. Nakamura", email: "bo@gmail.com", importedCompany: "Acme Robotics", importedPosition: "Co-Founder" },
  { id: "u-zed", handle: "zed", displayName: "Zed Zenith", email: "zed@elsewhere.io" },
];
const acme = { id: "c1", name: "Acme Robotics & Co, Inc.", domain: "acmerobotics.com" };

describe("normalization", () => {
  it("normalizes a person name for comparison without destroying it", () => {
    expect(normalizePersonName("Ann  Lee")).toBe("ann lee");
    expect(normalizePersonName("Bo Q. Nakamura")).toBe("bo q nakamura");
    expect(normalizePersonName("O'Brien, Seán")).toBe("obrien sean");
    expect(normalizePersonName("Ann Lee, Jr.")).toBe("ann lee");   // suffix stripped
    expect(normalizePersonName("Dr. Ann Lee")).toBe("ann lee");    // title stripped
    expect(normalizePersonName("")).toBe("");
  });

  it("normalizes a company name past its legal suffixes and punctuation", () => {
    expect(normalizeCompanyName("Acme Robotics & Co, Inc.")).toBe("acme robotics");
    expect(normalizeCompanyName("ACME ROBOTICS LLC")).toBe("acme robotics");
    expect(normalizeCompanyName("Bay Seed Fund III, L.P.")).toBe("bay seed fund iii");
    expect(normalizeCompanyName(null as any)).toBe("");
  });

  it("slugs a company for its URL", () => {
    expect(companySlug("Acme Robotics & Co, Inc.")).toBe("acme-robotics");
    expect(companySlug("  ")).toBe("");
  });

  it("reads email + url domains and knows the free providers", () => {
    expect(emailDomain("Ann@Acmerobotics.com")).toBe("acmerobotics.com");
    expect(emailDomain("nonsense")).toBeNull();
    expect(domainFromUrl("https://www.acmerobotics.com/careers")).toBe("acmerobotics.com");
    expect(domainFromUrl("not a url")).toBeNull();
    expect(isFreeEmailDomain("gmail.com")).toBe(true);
    expect(isFreeEmailDomain("acmerobotics.com")).toBe(false);
  });
});

describe("candidate generation is deterministic and never a link", () => {
  const person = { name: "Ann Lee", role: "Executive Officer" };

  it("finds the exact-name match and explains every signal it used", () => {
    const c = generateCandidates(person, acme, users);
    expect(c[0]!.userId).toBe("u-ann");
    expect(c[0]!.signals).toContain("name:exact");
    expect(c[0]!.signals).toContain("domain:email"); // ann@acmerobotics.com ↔ acmerobotics.com
  });

  it("never returns certainty — a deterministic candidate is still a question", () => {
    for (const c of generateCandidates(person, acme, users)) {
      expect(c.score).toBeGreaterThan(0);
      expect(c.score).toBeLessThan(1);
      expect(c.score).toBeGreaterThanOrEqual(CANDIDATE_FLOOR);
      // the shape carries no way to express "this IS them"
      expect(Object.keys(c).sort()).toEqual(["displayName", "handle", "score", "signals", "userId"]);
    }
  });

  it("keeps a weak initial+surname match, but ranks it under the exact one", () => {
    const c = generateCandidates(person, acme, users);
    const ids = c.map((x) => x.userId);
    expect(ids).toContain("u-ann2"); // "A. Lee"
    expect(ids.indexOf("u-ann")).toBeLessThan(ids.indexOf("u-ann2"));
  });

  it("ignores a free-mail domain that merely happens to match", () => {
    const freemail = generateCandidates({ name: "Bo Q. Nakamura", role: "Promoter" }, { id: "c2", name: "Gmail Inc", domain: "gmail.com" }, users);
    expect(freemail.find((c) => c.userId === "u-bo")!.signals).not.toContain("domain:email");
  });

  it("uses the LinkedIn company + position the importer has been writing all along", () => {
    const c = generateCandidates({ name: "Bo Q. Nakamura", role: "Promoter" }, acme, users);
    expect(c[0]!.userId).toBe("u-bo");
    expect(c[0]!.signals).toContain("linkedin:company");
    expect(c[0]!.signals).toContain("linkedin:position");
  });

  it("counts a prior self-declaration at the same company", () => {
    const declared = [{ ...users[3]!, declaredCompanyIds: ["c1"] }];
    const c = generateCandidates({ name: "Zed Zenith", role: "Director" }, acme, declared);
    expect(c[0]!.signals).toContain("declared:company");
  });

  it("returns NOTHING when no name signal is present, however well the domain matches", () => {
    const stranger: UserRef[] = [{ id: "u-x", handle: "x", displayName: "Completely Different", email: "x@acmerobotics.com" }];
    expect(generateCandidates(person, acme, stranger)).toEqual([]);
    expect(generateCandidates({ name: "", role: "Director" }, acme, users)).toEqual([]);
    expect(generateCandidates(person, acme, [])).toEqual([]);
  });

  it("is stable — the same inputs always produce the same order", () => {
    const a = generateCandidates(person, acme, users).map((c) => `${c.userId}:${c.score}`);
    const b = generateCandidates(person, acme, [...users].reverse()).map((c) => `${c.userId}:${c.score}`);
    expect(a).toEqual(b);
  });
});

describe("the model may only reorder candidates", () => {
  const person = { name: "Ann Lee", role: "Executive Officer" };

  it("applies a ranking over the candidate set", () => {
    const c = generateCandidates(person, acme, users);
    const reordered = applyRanking(c, ["u-ann2", "u-ann"]);
    expect(reordered.map((x) => x.userId)).toEqual(["u-ann2", "u-ann"]);
  });

  it("silently drops any id the model invented — it cannot add a person", () => {
    const c = generateCandidates(person, acme, users);
    const out = applyRanking(c, ["u-nonexistent", "u-ann"]);
    expect(out.map((x) => x.userId)).not.toContain("u-nonexistent");
    expect(out.length).toBe(c.length);
  });

  it("keeps unranked candidates rather than losing them, and survives junk", () => {
    const c = generateCandidates(person, acme, users);
    expect(applyRanking(c, []).map((x) => x.userId)).toEqual(c.map((x) => x.userId));
    expect(applyRanking(c, null as any).map((x) => x.userId)).toEqual(c.map((x) => x.userId));
    expect(applyRanking(c, ["u-ann2"]).length).toBe(c.length);
  });

  it("cannot change a score, only the order", () => {
    const c = generateCandidates(person, acme, users);
    const out = applyRanking(c, ["u-ann2", "u-ann"]);
    for (const o of out) expect(o.score).toBe(c.find((x) => x.userId === o.userId)!.score);
  });
});
